"""initial

Revision ID: bd61aa303a48
Revises: 
Create Date: 2026-04-20 18:52:55.851076
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd61aa303a48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coingecko_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('cmc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coins_coingecko_id'), 'coins', ['coingecko_id'], unique=True)
    op.create_index(op.f('ix_coins_symbol'), 'coins', ['symbol'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currencies', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_embedded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_external_id'), 'news_articles', ['external_id'], unique=True)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('circulating_supply', sa.Float(), nullable=True),
    sa.Column('max_supply', sa.Float(), nullable=True),
    sa.Column('ath', sa.Float(), nullable=True),
    sa.Column('ath_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ath_change_pct', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('atl_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atl_change_pct', sa.Float(), nullable=True),
    sa.Column('high_24h', sa.Float(), nullable=True),
    sa.Column('low_24h', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_coin_id'), 'market_data', ['coin_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('price_change_pct_24h', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_coin_ts', 'price_history', ['coin_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_price_history_coin_id'), 'price_history', ['coin_id'], unique=False)
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_coin_id'), table_name='price_history')
    op.drop_index('ix_price_coin_ts', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_market_data_coin_id'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_external_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_coins_symbol'), table_name='coins')
    op.drop_index(op.f('ix_coins_coingecko_id'), table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ###
